[package]
name = "carbide_core"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny" 