[package]
name = "carbide_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny" 